In [1]:
import pandas as pd 
import numpy as np 

data= pd.read_csv(r"C:\Users\User\Documents\GitHub\spam-detector\data\processed\spam_unified.csv")
print(data.iloc[0])

text      Gountiljurongpoint,crazy..Availableonlyinbugis...
label                                                     0
source                                                  sms
Name: 0, dtype: object

In [2]:
data.head(5)

                                                text  label source
0  Gountiljurongpoint,crazy..Availableonlyinbugis...      0    sms
1                           Oklar...Jokingwifuoni...      0    sms
2  Freeentryin2awklycomptowinFACupfinaltkts21stMa...      1    sms
3            Udunsaysoearlyhor...Ucalreadythensay...      0    sms
4  NahIdon'tthinkhegoestousf,helivesaroundherethough      0    sms

In [3]:
data.shape

(88076, 3)

In [4]:
data.info() #so there is no null values in the dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88076 entries, 0 to 88075
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    88076 non-null  object
 1   label   88076 non-null  int64
 2   source  88076 non-null  object
dtypes: int64(1), object(2)
memory usage: 2.0+ MB

In [5]:
data.duplicated().sum() #there are no duplicate values in the dataset

np.int64(0)

In [6]:
data.isnull().sum() #there are no null values in the dataset

text      0
label     0
source    0
dtype: int64

In [7]:
data["label"].value_counts()

label
1    44347
0    43729
Name: count, dtype: int64

In [10]:
import re

def url_count(text):
    """Number of URLs in the message."""
    return len(re.findall(r"http\S+|www\.\S+", text))


def exclamation_count(text):
    """Number of ! characters."""
    return text.count("!")


def capital_ratio(text):
    """Ratio of uppercase letters to all alphabetic letters."""
    letters = [c for c in text if c.isalpha()]

    if len(letters) == 0:
        return 0.0

    capitals = [c for c in letters if c.isupper()]
    return len(capitals) / len(letters)


def digit_ratio(text):
    """Ratio of digits to total characters."""
    if len(text) == 0:
        return 0.0

    digits = [c for c in text if c.isdigit()]
    return len(digits) / len(text)


def message_length(text):
    """Total number of characters."""
    return len(text)

In [11]:
data["url_count"] = data["text"].apply(url_count)

data["exclamation_count"] = data["text"].apply(exclamation_count)

data["capital_ratio"] = data["text"].apply(capital_ratio)

data["digit_ratio"] = data["text"].apply(digit_ratio)

data["message_length"] = data["text"].apply(message_length)

In [12]:
data.to_csv(r"C:\Users\User\Documents\GitHub\spam-detector\data\processed\spam_unified1.csv", index=False)

In [13]:
data.head(5)

,text,label,source,url_count,exclamation_count,capital_ratio,digit_ratio,message_length
0,"Gountiljurongpoint,crazy..Availableonlyinbugis...",0,sms,0,0,0.036145,0.000000,92
1,Oklar...Jokingwifuoni...,0,sms,0,0,0.111111,0.000000,24
2,Freeentryin2awklycomptowinFACupfinaltkts21stMa...,1,sms,0,0,0.103093,0.195312,128
3,Udunsaysoearlyhor...Ucalreadythensay...,0,sms,0,0,0.060606,0.000000,39
4,"NahIdon'tthinkhegoestousf,helivesaroundherethough",0,sms,0,0,0.042553,0.000000,49